engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
      extensions:
        - .js
        - .vue
ratings:
  paths:
    - "**.js"
    - "**.vue"
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
exclude_paths:
  - "__tests__/**/*"
