name: Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tags
        id: get-tags
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          TAGS=${DOCKERHUB_REPO_NAME}:latest
          TAGS=${TAGS},${DOCKERHUB_REPO_NAME}:$(echo "$VERSION" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1/')
          TAGS=${TAGS},${DOCKERHUB_REPO_NAME}:$(echo "$VERSION" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1.\2/')
          TAGS=${TAGS},${DOCKERHUB_REPO_NAME}:$(echo "$VERSION" | sed -E 's/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/\1.\2.\3/')
          echo ::set-output name=tags::${TAGS}
        env:
          DOCKERHUB_REPO_NAME: ${{ secrets.DOCKERHUB_REPO_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.get-tags.outputs.tags }}
