name: release-drafter
on:
  push:
    branches:
      - master
jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release draft
        uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
