name: Release
on:
  push:
    branches:
      - master
jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
